language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

script:
  - python -m pip install tox
  - python -m pip install -e .[build]
  - python -m pip install -e .[test]
  - tox -e build
  - tox -e py

deploy:
  provider: pypi
  username: "__token__"
  password: "${PYPI_TOKEN}"
  skip_existing: true
  skip_cleanup: true