language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - python -m pip install tox
  - pip3 install -e .[build]
  - pip3 install -e .[test]

script:
  - tox -e build
  - tox -e py

deploy:
  provider: pypi
  username: "__token__"
  password: "${PYPI_TOKEN}"
  skip_existing: true
  skip_cleanup: true