language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

addons:
  apt:
    packages:
      - default-jre

before_install:
  - python -m pip install --upgrade pip

install:
  - python -m pip install jingtrang pytest sh tox xsdata[cli]

script:
  - tox -e build
  - tox -e py

deploy:
  provider: pypi
  username: "__token__"
  password: "${PYPI_TOKEN}"
  skip_existing: false
  skip_cleanup: true
  distributions: "sdist bdist_wheel"