language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

addons:
  apt:
    packages:
      - default-jre

before_install:
  - python -m pip install jingtrang pytest sh tox xsdata xsdata[cli]
  - python setup.py build

install:
  - python setup.py install

script:
  - tox -e py

deploy:
  provider: pypi
  username: "__token__"
  password: "${PYPI_TOKEN}"
  skip_existing: true
  skip_cleanup: true