language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - python -m pip install tox pytest jingtrang xsdata xsdata[cli]
  - ./setup build

install:
  - ./setup install

script:
  - tox -e py

deploy:
  provider: pypi
  username: "__token__"
  password: "${PYPI_TOKEN}"
  skip_existing: true
  skip_cleanup: true